name: CI Security & Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    name: Lint, Unit Tests, Secret Scan, Trivy, and Docker Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install flake8 pytest

      # 4️⃣ Run Linter
      - name: Run Linter
        run: |
          flake8 . --max-line-length=88 --statistics

      # 5️⃣ Run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 6️⃣ Secret Detection
      - name: Detect secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true

      # 7️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 8️⃣ Trivy FS Scan (scan source code before build)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 1
          format: 'table'

      # 9️⃣ Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t python_image:latest .

      # 🔟 Trivy Image Scan (after build)
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: python_image:latest
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 1
          format: 'table'

      # 1️⃣1️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1️⃣2️⃣ Push Docker Image
      - name: Push Docker image to Docker Hub
        run: |
          docker tag pythonapp:latest preethi1100/python_image:latest
          docker push preethi1100/python_image:latest
