name: CI Security & Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    name: Lint, Secret Scan, Trivy, and Docker Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Linting (for Python)
      - name: Run Linter
        run: |
          pip install flake8
          flake8 . --max-line-length=88 --statistics

      # 4️⃣ Secret Detection
      - name: Detect secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true

      # 5️⃣ Trivy FS Scan (scan source code before build)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 1
          format: 'table'

      # 6️⃣ Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t pythonapp:latest .

      # 7️⃣ Trivy Image Scan (after build)
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pythonapp:latest
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 1
          format: 'table'
