name: CI Security & Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code with Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install flake8
          flake8 . --max-line-length=88 --statistics

  secrets-scan:
    name: Detect Secrets in Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: [lint, secrets-scan]
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t myapp:latest .
      - uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'myapp:latest'
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'